apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - username: system:node:{{`{{EC2PrivateDNSName}}`}}
      rolearn: {{ .Values.aws.role.node | quote}}
      groups:
        - system:bootstrappers
        - system:nodes
    - username: admin
      rolearn: {{ .Values.aws.role.user | quote }}
      groups:
        - system:masters
