apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - username: system:node:{{`{{EC2PrivateDNSName}}`}}
      rolearn: arn:aws:iam::{{ .Values.aws.account }}:role/hindsight-worker-role
      groups:
        - system:bootstrappers
        - system:nodes
    - username: admin
      rolearn: arn:aws:iam::{{ .Values.aws.account }}:role/hindsight-user-role
      groups:
        - system:masters
